version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: "db_container"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      args:
        - DEV=true
    container_name: "backend_container"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py makemigrations &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db


volumes:
  pgdata: