# Generated by Django 4.2.3 on 2023-08-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_recipe_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
