---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run : docker-compose run --rm backend bash -c "python manage.py test"
      - name: Lint
        run : docker-compose run --rm backend bash -c "flake8"
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
#        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          channel: '#actions'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
